#ifndef ENTITIES_DATA_HPP
#define ENTITIES_DATA_HPP

#define SPACING_FROM_WINDOW 100.f
#define BLOCK_COUNT_X 8
#define BLOCK_COUNT_Y 5
#define BLOCK_SPACE 110.f

#define LADDER_COUNT 4

#define MARIO_WIDHT 46.f
#define MARIO_HEIGHT 55.f

#endif